# C++异常简介及异常类创建

**C++内置了异常处理的----------try...catch...**

​	try语句处理正常代码逻辑

​	catch语句处理异常情况

​	try语句中的异常由对应的catch语句处理

​	同一个try语句可以跟多个catch语句

​	catch（...）用于处理所以类型异常，任何一种异常只能处理一次

​	`catch(Type t1)`处理某种数据异常，异常处理不存在默认类型转换

**通过throw抛出异常信息**

​	当前函数能够处理异常，程序继续往下执行

​	当前程序无法处理异常，则程序停止执行，并且返回至调用的地方，直至被处理为止，否则程序将停止执行

<font color=#008000>例如定义一个函数处理不同异常</font>

```cpp
void test()
{
    try
    {
        throw ‘a’;
    }
    catch(double a)
    {
        cout<<"double"<<endl;
    }
    catch(char c)
    {
        cout<<"char"<<endl;
    }
}
```

如果在main函数输出应该输出char



<font color=#008000>例如定义一个可以抛出异常的计算除法的函数</font>

```cpp
double divide(double a,double b)
{
    const double battle=0.000000000001;
    if(!(-battle<b)&&(b<battle))
    {
        result=a/b;
	}
    else
    {
        throw 0;//如果b接近0就抛出异常
    }
    return result;
}
```

<font color=#008000>在错误的main函数中使用</font>

```cpp
int main()
{
    cout<<"main begin"<<endl;
    divide(1,0);//执行到此处异常结束
    cout<<"main end"<<endl;
    return 0
}
```

运行程序输出main begin且程序异常结束，因为没有处理异常



<font color=#008000>在正确的main函数中使用</font>

```cpp
int main()
{
    cout<<"main begin"<<endl;
    try
    {
        int c=divide(1,0);
    }
    catch(...)
    {
        cout<<"异常扑捉成功"<<endl；
    }
    cout<<"main end"<<endl;
    return 0
}
```

运行程序输出main begin 异常扑捉成功 main end ，整个程序正常执行。

## C++中异常类的创建

匹配子类异常的catch放在上部，匹配父类异常的catch放在下部，创建相关类示意图。

![](E:\Git\mynote\C++数据结构笔记\示意图等存放\异常1.png)

抽象层的设计以及子类的设计

```cpp
#ifndef EXCEPTIOM_H
#define EXCEPTIOM_H

namespace dong {

//抛出异常宏函数
#define THROW_EXCEPTION(e,m) (throw e(m,__FILE,__LINE__))//抛出异常

//父类 抽象层
class Exception
{
protected:
    char *m_message;
    char *m_location;

    void init(const char *message,const char *file,int line);//相当于二级构造

public:
    Exception(const char * message);
    Exception(const char * file,int line);
    Exception(const char * message,const char * file,int line);

    Exception(const Exception& e);
    Exception& operator =(const Exception& e);

    virtual const char *message() const;
    virtual const char *location() const;
    virtual ~Exception()=0;
};

//子类 计算异常
class ArithmeticException : public Exception
{
public:
    ArithmeticException():Exception(nullptr){}
    ArithmeticException(const char * message):Exception(message){}
    ArithmeticException(const char * file,int line):Exception(file ,line){}
    ArithmeticException(const char * message,const char * file,int line):Exception(message,file ,line){}


    ArithmeticException(const ArithmeticException& e):Exception(e){}
    ArithmeticException& operator=(const ArithmeticException& e)
    {
        Exception::operator=(e);
        return *this;
    }
};

//子类 空指针异常
class NullPointerException : public Exception
{
public:
    NullPointerException():Exception(nullptr){}
    NullPointerException(const char * message):Exception(message){}
    NullPointerException(const char * file,int line):Exception(file ,line){}
    NullPointerException(const char * message,const char * file,int line):Exception(message,file ,line){}


    NullPointerException(const NullPointerException& e):Exception(e){}
    NullPointerException& operator=(const NullPointerException& e)
    {
        Exception::operator=(e);
        return *this;
    }
};

//子类 越界异常
class IndexOutofBoubdsException : public Exception
{
public:
    IndexOutofBoubdsException():Exception(nullptr){}
    IndexOutofBoubdsException(const char * message):Exception(message){}
    IndexOutofBoubdsException(const char * file,int line):Exception(file ,line){}
    IndexOutofBoubdsException(const char * message,const char * file,int line):Exception(message,file ,line){}


    IndexOutofBoubdsException(const IndexOutofBoubdsException& e):Exception(e){}
    IndexOutofBoubdsException& operator=(const IndexOutofBoubdsException& e)
    {
        Exception::operator=(e);
        return *this;
    }
};

//子类 内存不足异常
class NoenoughmemoryException : public Exception
{
public:
    NoenoughmemoryException():Exception(nullptr){}
    NoenoughmemoryException(const char * message):Exception(message){}
    NoenoughmemoryException(const char * file,int line):Exception(file ,line){}
    NoenoughmemoryException(const char * message,const char * file,int line):Exception(message,file ,line){}


    NoenoughmemoryException(const NoenoughmemoryException& e):Exception(e){}
    NoenoughmemoryException& operator=(const NoenoughmemoryException& e)
    {
        Exception::operator=(e);
        return *this;
    }
};

//子类 参数错误异常
class InvalidparameterException : public Exception
{
public:
    InvalidparameterException():Exception(nullptr){}
    InvalidparameterException(const char * message):Exception(message){}
    InvalidparameterException(const char * file,int line):Exception(file ,line){}
    InvalidparameterException(const char * message,const char * file,int line):Exception(message,file ,line){}


    InvalidparameterException(const InvalidparameterException& e):Exception(e){}
    InvalidparameterException& operator=(const InvalidparameterException& e)
    {
        Exception::operator=(e);
        return *this;
    }
};

}


#endif // EXCEPTIOM_H

```

抽象层的具体实现

```cpp
#include"exception.h"
#include<cstring>
#include<cstdlib>

using namespace std;

namespace dong {

void Exception::init(const char *message, const char *file, int line)
{
    m_message=strdup(message);//复制message的内容
    if(file!=nullptr)
    {
        char sl[16]={0};
        itoa(line,sl,10);
        m_location = static_cast<char *>(malloc(strlen(file) + strlen(sl) + 2));
        m_location = strcpy(m_location,file);
        m_location = strcat(m_location,":");
        m_location = strcat(m_location,sl);
    }
    else
    {
        m_location=nullptr;
    }
}

Exception::Exception(const char * message)
{
    init(message,nullptr,0);
}
Exception::Exception(const char * file,int line)
{
    init(nullptr,file,line);
}
Exception::Exception(const char * message,const char * file,int line)
{
    init(message,file,line);
}

Exception::Exception(const Exception& e)
{
    m_message=strdup(e.m_message);
    m_location=strdup(e.m_location);
}
Exception& Exception::operator =(const Exception& e)
{
    if(this != &e)
    {
        free(m_message);
        free(m_location);

        m_message=strdup(e.m_message);
        m_location=strdup(e.m_location);
    }
}
 const char * Exception::message() const
 {
     return m_message;
 }
 const char * Exception::location() const
 {
     return m_location;
 }

Exception::~Exception()
{
    free(m_message);
    free(m_location);
}
}
```

